micronaut:
  application:
    name: se09-device-service
  server:
    port: 9090
  http:
    services:
      vault:
        urls:
          - ${VAULT_URL}
datasources:
  default:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    hikari:
      connection-timeout: 10000
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE:2}
jpa:
  default:
    packages-to-scan:
      - 'se09.device.service'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        #show_sql: true
flyway:
  datasources:
    default:
      locations: classpath:databasemigrations
